# Generated by Django 6.0 on 2026-05-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='watermark_img',
        ),
    ]
