# Generated by Django 6.0 on 2026-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_remove_photo_watermark_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
